services:

  app-dev:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules # don't take node_modules into account
    container_name: todo-frontend-dev
    depends_on:
      - backend-dev
  
  debug-helper:
    image: busybox
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app-dev

  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data

  backend-dev:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: ./dev.Dockerfile
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis